export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_FAILURE = 'GET_SEARCH_FAILURE';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';

export const GET_CACHE_REQUEST = 'GET_CACHE_REQUEST';
export const GET_CACHE_FAILURE = 'GET_CACHE_FAILURE';
export const GET_CACHE_SUCCESS = 'GET_CACHE_SUCCESS';

export const QUERY = 'QUERY';
export const GET_RESULT_GROUPING = 'GET_RESULT_GROUPING';